name: scons

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install scons

      - name: Build
        run: |
          make

      - name: Test
        run: |
          make test
