name: scons

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install scons

      - name: Build
        run: |
          make

      - name: Test
        run: |
          make test
